# Generated by Django 2.0.6 on 2018-06-17 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20180617_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Имя'),
        ),
    ]
