# Generated by Django 2.0.6 on 2018-06-24 15:30

from django.db import migrations, models
import myproject.myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_document_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='features',
            field=models.BinaryField(blank=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='docfile',
            field=models.ImageField(upload_to='', validators=[myproject.myapp.models.validate_file_extension]),
        ),
    ]
